HouseRentManagementApp/HouseRentManagementApp/Models/HouseOwner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HouseRentManagementApp.Models
{
    public class HouseOwner
    {
        public int Id { get; set; }
         [Required(ErrorMessage = "Please enter a name")]
        public string Name { get; set; }
         [Required(ErrorMessage = "Please enter a NationalId")]
        public string NationalId {get;set;}

        [Range(0, int.MaxValue, ErrorMessage = "Please enter a valid  Number")]
        public string MobileNo {get;set;}
         [Required(ErrorMessage = "Please select your Occupation")]
        public int OccupationId {get;set;}

        public Occupation occupation {get;set;}

         [Required(ErrorMessage = "Please enter a password")]
        public string Password { get; set; }
          [NotMapped]
          [Required(ErrorMessage = "Please enter Confirm password")]
          [Compare("Password")]
         public string ConfirmPassword { get; set; }

          public List<Home> Homes { get; set; }
        
    }
}

HouseRentManagementApp/HouseRentManagementApp/Controllers/HouseOwnersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using Rotativa;
using System.Web.Mvc;
using HouseRentManagementApp.Models;

namespace HouseRentManagementApp.Controllers
{
    public class HouseOwnersController : Controller
    {
        private HouseRentDBContext db = new HouseRentDBContext();

        // GET: HouseOwners
        public ActionResult Index()
        {
            if (Session["HouseOwnerMobileNo"]!=null)
            {
                return RedirectToAction("Index", "Homes");
            }
           return View();
        }
        [HttpPost]
        public ActionResult Index(HouseOwner houseOwner)
        {
            var houseOwners = db.HouseOwners.ToList();

            HouseOwner houseOwnerSearch = houseOwners.Find(a => a.MobileNo == houseOwner.MobileNo && a.Password == houseOwner.Password);
            if(houseOwnerSearch!=null)
            {
                Session["HouseOwnerMobileNo"] = houseOwnerSearch.MobileNo;
                Session["HouseOwnerName"] = houseOwnerSearch.Name;
                Session["HouseOwnerId"] = houseOwnerSearch.Id;
                return RedirectToAction("Index","Homes");
            }
            else
            {
                ViewBag.LogInError = "Either Password or UserName Not match!";
                return View();
            }
          
        }

        // GET: HouseOwners/Details/5
        public ActionResult Details(HouseOwner houseOwner)
        {
            
            var houseOwners = db.HouseOwners.ToList();
            HouseOwner houseOwnerRegInf = houseOwners.Find(a => a.NationalId == houseOwner.NationalId);
            if (houseOwner == null)
            {
                return HttpNotFound();
            }
            return View(houseOwner);
        }

        // GET: HouseOwners/Create
        public ActionResult Create()
        {
            if (Session["HouseOwnerMobileNo"] != null)
            {
                return RedirectToAction("Index", "Homes");
            }
            ViewBag.OccupationId = new SelectList(db.Occupations, "Id", "Name");
            return View();
        }

        // POST: HouseOwners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( HouseOwner houseOwner)
        {
            
            
            ViewBag.OccupationId = new SelectList(db.Occupations, "Id", "Name", houseOwner.OccupationId);
            if (ModelState.IsValid)
            {
                var nationalIdWithMobileNos = db.NationalIdWithMobileNos.ToList();
                var houseOwners = db.HouseOwners.ToList();

               
                ViewBag.NationalId = nationalIdWithMobileNos.Find(a => a.NationalId == houseOwner.NationalId && a.MobileNo == houseOwner.MobileNo);
                ViewBag.ExistNationalId = houseOwners.Find(a => a.NationalId == houseOwner.NationalId);
                if (ViewBag.NationalId != null && ViewBag.ExistNationalId==null)
                {
                    db.HouseOwners.Add(houseOwner);
                    db.SaveChanges();
                    var houseOwners2 = db.HouseOwners.ToList();

                    HouseOwner houseOwnerSearch = houseOwners2.Find(a => a.MobileNo == houseOwner.MobileNo && a.Password == houseOwner.Password);
                   
                        Session["HouseOwnerMobileNo"] = houseOwnerSearch.MobileNo;
                        Session["HouseOwnerName"] = houseOwnerSearch.Name;
                        Session["HouseOwnerId"] = houseOwnerSearch.Id;

                        return RedirectToAction("Index", "Homes");
                    
                }

                else
                {
                    if (ViewBag.NationalId == null)
                    { ViewBag.NationalIdFound = "Id  not Found"; }
                    return View();
                }
                
                
            }

            return View(houseOwner);
        }

        // GET: HouseOwners/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseOwner houseOwner = db.HouseOwners.Find(id);
            if (houseOwner == null)
            {
                return HttpNotFound();
            }
            ViewBag.OccupationId = new SelectList(db.Occupations, "Id", "Name", houseOwner.OccupationId);
            return View(houseOwner);
        }

        // POST: HouseOwners/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,NationalId,MobileNo,OccupationId,UserName,Password,ConfirmPassword")] HouseOwner houseOwner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(houseOwner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OccupationId = new SelectList(db.Occupations, "Id", "Name", houseOwner.OccupationId);
            return View(houseOwner);
        }

        // GET: HouseOwners/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseOwner houseOwner = db.HouseOwners.Find(id);
            if (houseOwner == null)
            {
                return HttpNotFound();
            }
            return View(houseOwner);
        }

        // POST: HouseOwners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HouseOwner houseOwner = db.HouseOwners.Find(id);
            
            db.HouseOwners.Remove(houseOwner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult RentedRoomInfo()
        {
            if (Session["HouseOwnerMobileNo"] == null)
            {
                return RedirectToAction("Index");
            }
            var Homes = db.Homes.ToList();

            ViewBag.HomeId = Homes.Where(a => a.HouseOwnerId == (int)Session["HouseOwnerId"]);

            return View();
        }
        [HttpPost]
        public ActionResult RentedRoomInfo(int FlatId)
        {
            var rentedBys = db.RentedBys.Include(a => a.Flats.Homes).ToList();
            var rentedBy = rentedBys.Find(a => a.FlatId == FlatId && a.LeavingDate == null);

            return new ActionAsPdf("RentInfoPdf", rentedBy) { FileName = "RentInfos.pdf" }; ;
        }
        public ActionResult RentInfoPdf(RentedBy rentedBy1)
        {
            var rentedBys = db.RentedBys.Include(a => a.Flats.Homes.HouseOwners).ToList();
            var rentedBy = rentedBys.Find(a =>a.Id==rentedBy1.Id);

            var representatives = db.HouseRepresentatives.ToList();
            var representative = representatives.Find(a => a.Id == rentedBy.HouseRepresentative);
            ViewBag.HR = representative.Name;
            ViewBag.HRNo = representative.MobileNo;
            var flatMember = db.FlatMembers.Where(a => a.HouseRepresentativeId == representative.Id && a.LeavingDate==null).ToList();
            ViewBag.HouseName = rentedBy.Flats.Homes.Name;
            ViewBag.FlatNo= rentedBy.Flats.FlatNo;
            ViewBag.Owner = rentedBy.Flats.Homes.HouseOwners.Name;
            return View(flatMember);
        }
        public JsonResult GetFlatByHomeId(int HomeId)
        {

            var flats = db.Flats.ToList();
            List<Flat> flatsByHome = flats.Where(a => a.HomeId == HomeId).ToList();
            //return Json(course);

            return Json(flatsByHome, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetRentedRoomInfo(int FlatId)
        {
            var rentedBys=db.RentedBys.ToList();
            var rentedBy=rentedBys.Find(a=>a.FlatId==FlatId && a.LeavingDate==null);
            List<ViewRentedInfo> viewRentInfos = new List<ViewRentedInfo>();
            var representatives = db.HouseRepresentatives.ToList();
            if (representatives != null && rentedBy!=null)
            {
               
                var representative = representatives.Find(a => a.Id == rentedBy.HouseRepresentative);
                
                var flatMembers = db.FlatMembers.ToList();
                var flatMembersOfSameHouse = flatMembers.Where(a => a.HouseRepresentativeId == representative.Id && a.LeavingDate == null);
                if(flatMembersOfSameHouse==null)
                {
                    ViewRentedInfo viewRentInfo = new ViewRentedInfo()
                    {
                        RepresentativeName = representative.Name,
                        RepresentativeContactNo = representative.MobileNo,
                    };
                    viewRentInfos.Add(viewRentInfo);
                }
                else
                {
                    foreach (var flatMember in flatMembersOfSameHouse)
                    {
                        ViewRentedInfo viewRentInfo = new ViewRentedInfo()
                        {
                            RepresentativeName = representative.Name,
                            RepresentativeContactNo = representative.MobileNo,
                            ContactNo = flatMember.MobileNo,
                            MemberName = flatMember.Name
                        };
                        viewRentInfos.Add(viewRentInfo);

HouseRentManagementApp/HouseRentManagementApp/Views/HouseOwners/Create.cshtml
@model HouseRentManagementApp.Models.HouseOwner

@{
    
    ViewBag.Title = "CreateHouseOwner";
    string NationalId = ViewBag.NationalIdFound;
    
}
@if (NationalId != null)
{
    <label class="alert-warning">Either National Id Not Found Or National Id is not Synching with Mobile No. </label>
}
@if (ViewBag.ExistNationalId != null)
{
    <label class="alert-warning">Nationl Id Already Exist</label>
}
<h2>Register House Owner</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NationalId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.NationalId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NationalId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OccupationId, "OccupationId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OccupationId","")
                @Html.ValidationMessageFor(model => model.OccupationId, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HouseRentManagementApp/HouseRentManagementApp/Views/HouseOwners/Delete.cshtml
@model HouseRentManagementApp.Models.HouseOwner

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HouseOwner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.occupation.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.occupation.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NationalId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NationalId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MobileNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobileNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConfirmPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfirmPassword)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HouseRentManagementApp/HouseRentManagementApp/Views/HouseOwners/Details.cshtml
@model HouseRentManagementApp.Models.HouseOwner

@{
    Layout = null;
    ViewBag.Title = "HouseOwnerReg ";
}

<h2>House Owner Information</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.occupation.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.occupation.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NationalId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NationalId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MobileNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobileNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

       

    </dl>
</div>

HouseRentManagementApp/HouseRentManagementApp/Views/HouseOwners/Edit.cshtml
@model HouseRentManagementApp.Models.HouseOwner
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HouseOwner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NationalId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NationalId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NationalId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OccupationId, "OccupationId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OccupationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OccupationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HouseRentManagementApp/HouseRentManagementApp/Views/HouseOwners/Index.cshtml
@model HouseRentManagementApp.Models.HouseOwner

@{
    ViewBag.Title = "HouseOwner";
    string logInError = ViewBag.LogInError;
}

<h2>House Owner Sign In</h2>
<br />
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-group">
        @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Sign In" class="btn btn-default" />
            @if (logInError != null)
            {
                <label class="alert-warning">@logInError</label>
            }
            @Html.ActionLink("Regiser", "Create", "HouseOwners")
        </div>
    </div>
   

}

HouseRentManagementApp/HouseRentManagementApp/Views/HouseOwners/RentInfoPdf.cshtml
@model IEnumerable<HouseRentManagementApp.Models.FlatMember>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Flat Renter Info</title>
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

</head>

<body>

    <div class="heading2">
        <center>
            <h2>Rented Flat Information</h2>
            <table>
                <tr><td><h5>House Name:</h5></td><td><h5>@ViewBag.HouseName</h5></td></tr>
                <tr><td><h5>House Owner:</h5></td><td><h5>@ViewBag.Owner</h5></td></tr>
                <tr><td><h5>Flat No:</h5></td><td><h5>@ViewBag.FlatNo</h5></td></tr>
                <tr><td><h5>Renter Name:</h5></td><td><h5>@ViewBag.HR</h5></td></tr>
                <tr><td><h5>Renter Mobile No:</h5></td><td><h5>@ViewBag.HRNo</h5></td></tr>


            </table>
        </center>
       


    </div>
    <div>
        <center> <h3><mark>Flat Members List</mark></h3></center>
    </div>
    <div class="table-responsive">
        <table title="House Member List" class="table">
            <thead>
                <tr>
                    <td>Member Name</td>
                    <td>Mobile No</td>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td> @item.Name</td>
                        <td>@item.MobileNo</td>
                    </tr>

                }


            </tbody>

        </table>
    </div>
    <br />
    <br />
   <p class="text-left">@ViewBag.Owner</p> 
    <p class="text-right">@ViewBag.HR</p>


    <div>

    </div>
                                                @*<script src="~/Scripts/jquery-ui-1.12.1.js"></script>

                                                      <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js">
                                            </script>


        <script src="~/Scripts/jquery-1.12.4.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>

                                                *@

   
</body>
</html>

HouseRentManagementApp/HouseRentManagementApp/Views/HouseOwners/RentedRoomInfo.cshtml
@{
    ViewBag.Title = "RentedRoomInfo";
}
<link href="~/Content/DataTables-1.9.4/media/css/jquery.dataTables.css" rel="stylesheet" />
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<h2>RentedRoomInfo</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

   <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label for="HomeId" class="control-label col-md-2">Select Home</label>
            <div class="col-md-10">
                <select name="HomeId" id="HomeId">
                    <option>--Select--</option>
                    @foreach (var Home in ViewBag.HomeId)
                    {
                        <option value="@Home.Id">@Home.Name</option>
                    }


                </select>
            </div>
        </div>



        <div class="form-group">

            <label for="FlatId" class="control-label col-md-2">Select Flat</label>
            <div class="col-md-10">
                <select name="FlatId" id="FlatId">
                    <option>--Select--</option>
                </select>
            </div>
        </div>


               
        <div class="form-group">
            <label for="HouseRepresentativeName" class="control-label col-md-2">House Representative Name</label>
            <div class="col-md-10">
                <input type="text" id="HouseRepresentativeName" />
            
            </div>
        </div>
        <div class="form-group">
            <label for="HouseRepresentativeContactNo" class="control-label col-md-2">House Representative Mobile No</label>
            <div class="col-md-10">
                <input type="text" id="HouseRepresentativeContactNo" />
            </div>
        </div>
        <div class="form-group">
            <table id="myTable" class="table table-bordered table-hover table-striped">
                <thead>
                    <tr>
                        <th>Member Name</th>
                        <th>Mobile No</th>
                    </tr>
                </thead>
                <tbody id="tableBody"></tbody>
            </table>
        </div>


       

        


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Make Pdf" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
                 @Scripts.Render("~/bundles/jqueryval")

         <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>

         <script>

                 $(document).ready(function () {

                     $("#HomeId").change(function () {
                         var HmeId = $("#HomeId").val();

                         $("#FlatId").empty();
                         $("#FlatId").append('<option value="">Select</option>');
                         var json = { HomeId: HmeId };
                         $.ajax({
                             type: "POST",
                             url: '/RentedBies/GetFlatByHomeId',
                             contentType: "application/json; charset=utf-8",
                             data: JSON.stringify(json),
                             success: function (data) {

                                 $.each(data, function (key, value) {
                                     $("#FlatId").append('<option value="' + value.Id + '">' + value.FlatNo + '</option>');


                                 });
                             }
                         });
                     });
                   var table = $("#myTable").DataTable();
                $("#FlatId").change(function () {
                    var FtId = $("#FlatId").val();

                    $("#myTable").show();
                    $("#tableBody").empty();
                    var json = { FlatId: FtId };
                    $.ajax({
                        type: "POST",

                        url: '/HouseOwners/GetRentedRoomInfo',

                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {


                            $.each(data, function (key, value) {
                                $("#HouseRepresentativeName").val(value.RepresentativeName);
                                $("#HouseRepresentativeContactNo").val(value.RepresentativeContactNo);
                                $("#tableBody").append('<tr><td>' + value.MemberName + '</td><td>' + value.ContactNo +'</td></tr>');
                            });
                        }
                    });
                });

                 });

        </script>
             }